-- Supabase SQL Commands for the Orders System

-- 1. Create the orders table
CREATE TABLE IF NOT EXISTS public.orders (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID REFERENCES auth.users(id) ON DELETE SET NULL, -- Soft reference to the user placing the order
    user_email TEXT,
    customer_name TEXT NOT NULL,
    customer_phone TEXT NOT NULL,
    delivery_address TEXT NOT NULL,
    delivery_instructions TEXT,
    items JSONB NOT NULL DEFAULT '[]'::jsonb, -- Store the cart items as JSON
    subtotal NUMERIC(10, 2) NOT NULL DEFAULT 0.00,
    tax NUMERIC(10, 2) NOT NULL DEFAULT 0.00,
    delivery_fee NUMERIC(10, 2) NOT NULL DEFAULT 0.00,
    total NUMERIC(10, 2) NOT NULL DEFAULT 0.00,
    payment_method TEXT NOT NULL,
    payment_status TEXT NOT NULL DEFAULT 'pending',
    payment_intent_id TEXT,
    order_status TEXT NOT NULL DEFAULT 'pending', -- Expected values: 'pending', 'accepted', 'cancelled'
    verification_code TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- 2. Add an updated_at trigger for real-time tracking
CREATE OR REPLACE FUNCTION update_modified_column()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER update_orders_modtime
BEFORE UPDATE ON public.orders
FOR EACH ROW EXECUTE PROCEDURE update_modified_column();

-- 3. Enable Row Level Security (RLS) policies
-- Note: As a public/guest checkout, we are primarily inserting orders from the server backend
-- which bypasses RLS using the service_role key.
ALTER TABLE public.orders ENABLE ROW LEVEL SECURITY;

-- Allow users to read their own orders (if they are logged in)
CREATE POLICY "Users can read their own orders"
    ON public.orders
    FOR SELECT
    USING (auth.uid() = user_id);

-- Allow admins to read all orders (Alternatively, the service_role key does this automatically)
CREATE POLICY "Admins can read all orders"
    ON public.orders
    FOR SELECT
    USING (auth.jwt() ->> 'role' = 'service_role');

-- Allow admins to update orders (i.e. changing status from pending to accepted)
CREATE POLICY "Admins can update orders"
    ON public.orders
    FOR UPDATE
    USING (auth.jwt() ->> 'role' = 'service_role');
